---
title: "Reproducibilidad y Control de Versiones para las Ciencias Sociales"
bibliography: zlibrary.bib
csl: apa6.csl
output:
  html_document: 
    highlight: monochrome
    includes:
      in_header: academicons.html
    toc: yes
    toc_float:
      collapsed: no
css: sty|e-opsc.css      
---

<div style="text-align: right"> **Julio César Iturra Sanhueza** </div>

# Presentación

El presente documento tiene el objetivo de introducir a investigadores e investigadoras de las Ciencias Sociales al uso de herramientas para el control de versiones para la realización de investigación que permita cumplir con los estándares de [**Reproducibilidad**, **Apertura** y **Transparencia**](osf.html) [@Nosek2015]. 



## Git

Git fue creado por Linus Torvald para realizar control de versiones en el desarrollo de Linux  [@loeliger2012version].


## Clone, Push, Commit, Pull, Branch: ¿de qué se trata?.


* Crear username


```{git}
git config --global user.email "jciturra@uc.cl"
git config --global user.name "jciturras"
```

* Crear un repositorio

[https://git-scm.com/](Git)


* Trabajar con GitBash

### Clone

```{git}
cd C:\Users\JC\Desktop\git-julio # desde acá...
cd C:/Users/JC/Desktop/git-julio # a esto...
cd C:/Users/JC/Desktop/git-julio/xaringan-coes

# Hay que dar vuelta los slash
git clone https://github.com/jciturras/xaringan-coes.git
```

### Commit

```{git}
git add README.md
git status 
git commit -m "Nuestro Primer Commit" 
```

Ahora, si deseamos ver el mensaje de nuestro último commit para identificar su "hash" (id):

```{git}
git log
```


En el caso de que queramos deshacer el último commit:
```{git}
git reset --hard 00111112222333aaaabbbbbccccddd222
```


### Push

```{git}
git push origin master
```


### Pull

```{git}
git pull
```

### Branch

1. Para checkear en qué branch estamos.
2. La Branch "vigente" debería aparecer con un ``*``   

```{git}
git branch 
```

3. Creamos una nueva branch.

```{git}
git branch branch01  
```

4. Seleccionamos la nueva branch que se llame **"branch01"**.

```{git}
git checkout branch01  
```

5. Chequeamos cuál es la branch vigente.

```{git}
git branch 
```


# Servidores

# Editores 

* Atom

* RStudio

* GitHub Desktop


# Referencias
